#!/usr/bin/bash

: ${XDG_CONFIG_HOME:="$HOME/.config"}
: ${XDG_CACHE_HOME:="$HOME/.cache"}

[[ ! -d $XDG_CONFIG_HOME/wget ]] && mkdir "$XDG_CONFIG_HOME/wget"
[[ ! -d $XDG_CACHE_HOME/wget ]] && mkdir "$XDG_CACHE_HOME/wget"

echo hsts-file \= "$XDG_CACHE_HOME"/wget/wget-hsts > "$XDG_CONFIG_HOME/wget/wgetrc"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../bash/profile-link.sh"
link_bash_profile wget
