#!/usr/bin/bash

: "${XDG_DATA_HOME:=$HOME/.local/share}"

export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
  sh -s -- -y

# shellcheck source=/dev/null
source "$CARGO_HOME/env"

rustup toolchain install stable

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../bash/profile-link.sh
source "$SCRIPT_DIR/../bash/profile-link.sh"
link_bash_profile rust
