#!/usr/bin/bash

for i in *.mp3; do
  ffmpeg -i "$i" -i cover.jpg -map 0:0 -map 1:0 -c copy \
         -id3v2_version 3 \
         -metadata:s:v title="Album cover" \
         -metadata:s:v comment="Cover (front)" "_$i"
  mv "_$i" "$i"
done
