#!/usr/bin/bash

: "${GITHUB_USER:="$USER"}"
: "${REPOS_DIR:="$HOME/repos"}"
: "${NOTEBOX_ROOT_DIR:="$REPOS_DIR/github.com/$GITHUB_USER/notebox"}"

nb_create() {
  local title note_dir
  title="$*"

  note_dir="$NOTEBOX_ROOT_DIR/$(isosec)"
  mkdir -p "$note_dir"

  echo "# $title" >> "$note_dir/README.md"
  command $EDITOR "$note_dir/README.md"

  if [[ -z $title ]]; then return; fi

  read -rp "Commit? " ans
  if [[ $ans =~ [Yy].* ]]; then
    cd "$NOTEBOX_ROOT_DIR" && git add "$note_dir" && git commit -m "$title"
  fi
}

nb_search() {
  cd "$NOTEBOX_ROOT_DIR"
  git grep -ir "${@//\ /\.\*}"
}

_nb(){
  local cmd
  if [[ -n "$1" ]]; then
    cmd="$1"; shift
  fi

  # TODO: `last` command: prints the last note folder created.
  # TODO: `grep` command: does a grep on the whole notebox
  case "$cmd" in
    create) nb_create "$@" ;;
    search) nb_search "$@" ;;
    "" | * ) return 1 ;;
  esac
}

_nb "$@"
